Features
alexawesomecode/project-restaurant-js pull request #1
Opened 2020-03-05 20:27 UTC by alexawesomecode

Hello

Everything is working:

1. Use only JS to create elements and css
2. Different js files for tab
3. tab animation done in js
4. cool layout

2020-03-05 22:02 UTC, bellom requested changes
## Hi @alexawesomecode  :clap: 

### Awesome job so far!! :+1:  

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
1. **May I know the reason why am seeing commits from two different GitHub users, seem @aalexu84 ain't one of the MIcroverse students. (I need to get back to you on this).**

2. **Kindly check my comments below.**

3. **You need to fix the linter's errors. and solve the merge conflicts**
![image](https://user-images.githubusercontent.com/31897434/73417568-ca44bd00-4318-11ea-8a5e-fedabd629b8c.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/

Note: Do not make changes to the given config file, check out the [microverse-linter-config](https://github.com/microverseinc/linters-config/tree/master/javascript)

**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-03-05 22:02 UTC, bellom commented on src/onload.js
> +  // content styling
Kindly move this to CSS files
![image](https://user-images.githubusercontent.com/31897434/76028638-527b3b00-5f33-11ea-8175-1e910254adcf.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/
Under General.

2020-03-05 22:02 UTC, bellom commented on src/setStyle.js
> + .central p {
Let's have our CSS styling in CSS file, we shouldn't write JS and CSS together.
![image](https://user-images.githubusercontent.com/31897434/76028638-527b3b00-5f33-11ea-8175-1e910254adcf.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/
 Check Under General.

2020-03-06 14:06 UTC, alexawesomecode commented on src/onload.js
> +  // content styling
Hello Olu

Thanks for your insightful review, it was very clear, I will work on the changes.

About the issue why appears another user as doing a commit (alexu84): I did this commit after I re-installed my Debian Linux Machine. I did it without configuring the git user.email or git.user, so by my mistake used the default user and domain from my machine "alex@debian" to the commit.

I have already had this problem before, on a previous project, after I re-installed my machine and forgot to set the credentials.

I thought It was a bug that you could just change your email, commit and it appears as the other person did the commit. I played with this doing commits from various people in another repo. I reported this to github but its a feature built it on github, indeed!

I have tried and tried to amend the commit name and email but I still coulnt figure it out

Sorry for the confusion

2020-03-06 23:30 UTC, shloch requested changes
## hello @alexawesomecode 

nice interface and shaky animation
![Screen Shot 2020-03-07 at 12 31 22 AM](https://user-images.githubusercontent.com/40712459/76130326-b0c71d00-600a-11ea-8891-b5e114a654e2.png)

I guess there's one debugging to do, the first menu doesn't work, when i click on `"DELICIOUS DISHES"`, it doesn't load and i get this console error, you can see from screenshot

### Let's get to debugging......

2020-03-07 00:20 UTC, bellom approved these changes
## Hi @alexawesomecode  :clap: 

**Great work making all the necessary corrections from the previous review.**

**Note:**Make sure to fix conflicts before submitting for review next time.

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next project :slightly_smiling_face:_ 

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-07-01 20:16 UTC, merged